plugins {
    id 'java-library'
}

dependencies {
    api libs.com.github.philippheuer.events4j.events4j.handler.simple
    api libs.com.github.twitch4j.twitch4j
    api libs.com.github.jwdeveloper.tiktok.live.java.client
    api libs.org.json.json
}

java {
    sourceCompatibility = JavaVersion.VERSION_16
    targetCompatibility = JavaVersion.VERSION_16
}

tasks.withType(JavaCompile).configureEach {
    options.release = 16
}