# This is the configuration file for ChatPointsTTV. For a fresh copy of this file, go to https://github.com/GospelBG/ChatPointsTTV/blob/master/src/main/resources/config.yml
# For more information about how to use this file, refer to the config.yml instructions in the README file at https://github.com/GospelBG/ChatPointsTTV/blob/master/README.md

CHANNEL_USERNAME: {YOUR CHANNEL}

# Set up here your channel point rewards.
# Add as many lines as needed. Replace {REWARD_NAME} with your reward's name, EXACTLY as it is on Twitch.

# {REWARD_NAME}: {ACTION}

# For the action, follow this format:
#     SPAWN {ENTITY_NAME_IN_CAPS} {AMOUNT}
#     RUN {TARGET / CONSOLE} {COMMAND}

# If your reward contains a text input, you can reference it as:
#     {TEXT} **ONLY SUPPORTED ON CHANNEL POINTS**

# Leave any reward class empty to disable it.
REWARDS:
  {REWARD NAME}: {ACTION}

# Follow the same format as the Channel Point Rewards, replacing the name of the reward for the minimum ammount of bits that needs to be cheered.
CHEER_REWARDS:
  {100/500/1000...}: {ACTION}

# Follow the same format as the Channel Point Rewards, replacing the name of the reward for the desired sub tier: TWITCH_PRIME/TIER1/TIER2/TIER3.
# Also you can enter an AMOUNT on GIFT_REWARDS to toggle actions with sub gifting
SUB_REWARDS:
  {TWITCH_PRIME/TIER1/TIER2/TIER3}: {ACTION}

GIFT_REWARDS:
  {AMOUNT}: {ACTION}

# Whether the plugin should log to the console when a user (GospelBG cheered 300 bits!; GospelBG has subscribed with a Tier 1 sub!; ...)
LOG_EVENTS: true

# Customize the in-game title.
# You can use the following options:

#  Colors:
#   AQUA, BLACK, BLUE, DARK_AQUA, DARK_BLUE, DARK_GRAY, DARK_GREEN, DARK_PURPLE,
#   DARK_RED, GOLD, GRAY, GREEN, ITALIC, LIGHT_PURPLE, RED, WHITE, YELLOW

#  Formatting:
#   BOLD
#   STRIKETHROUGH
#   UNDERLINE

# Misc:
#   MAGIC

REWARD_NAME_BOLD: true
COLORS:
  USER_COLOR: GOLD

  REWARD_NAME_COLOR: YELLOW
  CHEER_COLOR: DARK_PURPLE
  SUB_COLOR: YELLOW
  GIFT_COLOR: RED

# Customize the on-screen text that is broadcasted to players.
# Viewer's username and their reward will be autommatically added to the message.

STRINGS:
  REDEEMED_STRING: "has redeemed" # Whitespaces on the start and end of the string are added automatically.
  CHEERED_STRING: "cheered" #..."100 bits"
  SUB_STRING: "has subscribed with" #..."Tier 1/2/3/Prime"
  GIFT_STRING: "gifed" #..."5 subs"