# This is the configuration file for ChatPointsTTV. For a fresh copy of this file, go to https://github.com/GospelBG/ChatPointsTTV/blob/master/src/main/resources/config.yml
# For more information about how to use this file, refer to the config.yml instructions in the README file at https://github.com/GospelBG/ChatPointsTTV/blob/master/README.md

# Comment a line (#) to disable platform
TWITCH_CHANNEL_USERNAME: {YOUR TWITCH CHANNEL}
TIKTOK_CHANNEL_USERNAME: {YOUR TIKTOK CHANNEL} # Without the "@" symbol

# Uncomment the following lines (remove the # symbol at the start of the line) to use a key-based authentication instead of the browser login.
# It should be used in remote environments which do not have a web browser (i.e. a standalone hosted server)
# TWITCH_CLIENT_ID: your_client_id_here
# TWITCH_ACCESS_TOKEN: your_access_token_here

# Whether the plugin shoud automatically connect to TikTok and to Twitch (acwhen a key-based authentication is used for this platform).
AUTO_LINK: true

# Whether your stream chat should show up in the in-game chat
SHOW_CHAT: true

# Uncomment the following line and add chat bot usernames (in lowercase) to this list to prevent their messages to display on the in-game chat.
# CHAT_BLACKLIST:

# Set up here your channel point rewards.
# Add as many lines as needed. Replace [REWARD NAME] with your reward's name, EXACTLY as it is on Twitch.

# REWARD_NAME:
#    - ACTION

# For the action, follow this format:
#     SPAWN {ENTITY_NAME} {AMOUNT}
#     RUN {TARGET / CONSOLE} {COMMAND}
#     GIVE {ITEM} {AMOUNT}

# If your reward contains a text input, you can reference it as:
#     {TEXT} **ONLY SUPPORTED ON CHANNEL POINTS**

# Leave any reward class empty to disable it.
TWITCH_CHANNEL_POINTS_REWARDS:
  [REWARD NAME]:
    - {ACTION 1}
    - {ACTION 2}

# Put the desired action after the colon in the form of a list. You musn't add a "Reward Name".
TWITCH_FOLLOW_REWARDS:
  - {ACTION}
  - {ACTION}

# Follow the same format as the Channel Point Rewards, replacing the name of the reward for the minimum ammount of bits that needs to be cheered.
TWITCH_CHEER_REWARDS:
  [BITS AMOUNT]:
    - {ACTION}

# Follow the same format as the Channel Point Rewards, replacing the name of the reward for the desired sub tier: TWITCH_PRIME/TIER1/TIER2/TIER3.
# Also you can enter an AMOUNT on TWITCH_GIFT_REWARDS to toggle actions with sub gifting
TWITCH_SUB_REWARDS:
  [TWITCH_PRIME]:
    - {ACTION}
  [TIER1/2/3]:
    - {ACTION}

TWITCH_GIFT_REWARDS:
  [AMOUNT]:
    - {ACTION}

# Put the desired action after the colon in the form of a list. You musn't add an "Item Name".
TIKTOK_FOLLOW_REWARDS:
  - {ACTION}

TIKTOK_GIFT_REWARDS:
  [ITEM NAME]:
    - {ACTION 1}
    - {ACTION 2}

TIKTOK_SHARE_REWARDS:
  - {ACTION}

# Add glow effect to spawned mobs
MOB_GLOW: true
# Set chatter's name to spawned mobs
DISPLAY_NAME_ON_MOB: true

# Whether the plugin should log to the console when a user (GospelBG cheered 300 bits!; GospelBG has subscribed with a Tier 1 sub!; ...)
LOG_EVENTS: true

# Customize the in-game title.
# You can use the following options:

#  Colors:
#   AQUA, BLACK, BLUE, DARK_AQUA, DARK_BLUE, DARK_GRAY, DARK_GREEN, DARK_PURPLE,
#   DARK_RED, GOLD, GRAY, GREEN, ITALIC, LIGHT_PURPLE, RED, WHITE, YELLOW

#  Formatting:
#   BOLD
#   STRIKETHROUGH
#   UNDERLINE

# Misc:
#   MAGIC

REWARD_NAME_BOLD: true
COLORS:
  USER_COLOR: GOLD
  ACTION_COLOR: YELLOW

# Customize the on-screen text that is broadcasted to players.
# Viewer's username and their reward will be autommatically added to the message.

STRINGS:
  REDEEMED_STRING: "has redeemed" # Whitespaces on the start and end of the string are added automatically.
  FOLLOWED_STRING: "has started following"
  CHEERED_STRING: "cheered" #..."100 bits"
  SUB_STRING: "has subscribed with" #..."Tier 1/2/3/Prime"
  GIFT_STRING: "gifted" #..."5 subs"
  SHARED_STRING: "has shared this LIVE"