# This is the configuration file for ChatPointsTTV. For a fresh copy of this file, go to https://github.com/GospelBG/ChatPointsTTV/blob/master/src/main/resources/config.yml
# For more information about how to use this file, refer to the config.yml instructions in the README file at https://github.com/GospelBG/ChatPointsTTV/blob/master/README.md

# Username(s) of the streamer's channels. In case of multiple streamers, must be set as a list: ["channel_1", "channel_2", "..."]
CHANNEL_USERNAME: {YOUR CHANNEL}

# Uncomment the following lines (remove the # symbol at the start of the line) to use a key-based authentication instead of the browser login.
# It should be used in remote environments which do not have a web browser (i.e. a standalone hosted server)
# CUSTOM_CLIENT_ID: your_client_id_here
# CUSTOM_ACCESS_TOKEN: your_access_token_here

# Whether the plugin shoud automatically connect to Twitch when a key-based authentication is used.
AUTO_LINK_CUSTOM: true

# Whether your stream chat should show up in the in-game chat
SHOW_CHAT: true

# Uncomment the following line and add chat bot usernames (in lowercase) to this list to prevent their messages to display on the in-game chat.
# CHAT_BLACKLIST:

# Set up here your channel point rewards.
# Add as many lines as needed. Replace [REWARD NAME] with your reward's name, EXACTLY as it is on Twitch.

# REWARD_NAME:
#    - ACTION

# For the action, follow this format:
#     SPAWN {ENTITY_NAME} [AMOUNT] [TARGET USER]
#     RUN {TARGET / CONSOLE} {COMMAND}
#     GIVE {ITEM} [AMOUNT] [TARGET USER]
#     TNT {AMOUNT} [EXPLOSION TIME IN TICKS]

# Extra fields:
#     {TEXT} Channel Points User Input
#     {USER} Viewer's username

# To add a streamer-specific reward add the actions inside a list named as the desired channel.
# To target all channels use "default" as the list key.

# Leave any reward class empty to disable it.
CHANNEL_POINTS_REWARDS:
  [REWARD NAME]:
    - {ACTION 1}
    - {ACTION 2}

# Put the desired action after the colon as a list. You musn't add a "Reward Name".
FOLLOW_REWARDS:
  - {ACTION}
  - {ACTION}

# Follow the same format as Channel Point Rewards, replacing the name of the reward for the minimum ammount of bits that needs to be cheered.
CHEER_REWARDS:
  [BITS AMOUNT]:
    - {ACTION}

# Follow the same format as Channel Point Rewards, replacing the name of the reward for the desired sub tier: TWITCH_PRIME/TIER1/TIER2/TIER3.
# Also you can enter an AMOUNT on GIFT_REWARDS to toggle actions with sub gifting
SUB_REWARDS:
  [TWITCH_PRIME]:
    - {ACTION}
  [TIER1/2/3]:
    - {ACTION}

GIFT_REWARDS:
  [AMOUNT]:
    - {ACTION}

# Add glow effect to spawned mobs
MOB_GLOW: true
# Set chatter's name to spawned mobs
DISPLAY_NAME_ON_MOB: true

# Whether the plugin should log to the console when a user (GospelBG cheered 300 bits!; GospelBG has subscribed with a Tier 1 sub!; ...)
LOG_EVENTS: true

# In-game event alerts mode.
#     none: Disables in-game alerts
#     chat: Displays a message in the chat
#     title: Shows a title splash message
#     all: Uses both "chat" and "title" alerts
INGAME_ALERTS: chat

# You can use the following options:

#  Colors:
#   AQUA, BLACK, BLUE, DARK_AQUA, DARK_BLUE, DARK_GRAY, DARK_GREEN, DARK_PURPLE,
#   DARK_RED, GOLD, GRAY, GREEN, ITALIC, LIGHT_PURPLE, RED, WHITE, YELLOW

#  Formatting:
#   BOLD
#   STRIKETHROUGH
#   UNDERLINE

# Misc:
#   MAGIC

REWARD_NAME_BOLD: true
COLORS:
  USER_COLOR: GOLD
  ACTION_COLOR: YELLOW

# Customize the on-screen text that is broadcasted to players.
# Viewer's username and their reward will be autommatically added to the message.

STRINGS:
  REDEEMED_STRING: "has redeemed" # Whitespaces on the start and end of the string are added automatically.
  FOLLOWED_STRING: "has started following"
  CHEERED_STRING: "cheered" #..."100 bits"
  SUB_STRING: "has subscribed with a" #..."Tier 1/2/3/Prime"
  GIFT_STRING: "gifted" #..."5 subs"