name: ChatPointsTTV
version: ${project.version}
author: GospelDev
website: ${project.url}
main: 'me.gosdev.chatpointsttv.ChatPointsTTV'
api-version: '1.13'
libraries:
  - com.github.twitch4j:twitch4j:1.21.0
  - com.github.philippheuer.events4j:events4j-handler-simple:0.12.2
  - org.json:json:20240303

commands:
  twitch:
    description: Manage ChatPointsTTV from this command. Use "/twitch help" to get a full list of commands.
    usage: /twitch <function>
    permission: chatpointsttv.manage

permissions:
  chatpointsttv.manage:
    default: op

  chatpointsttv.target:
    default: false

  chatpointsttv.broadcast:
    default: true